apiVersion: v1
kind: Service
metadata:
  labels:
    app: gzweb
  name: gzweb
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gzweb
